### ISSUE TITLE
Api přístupné ze stránek Kasiopei

### ISSUE THREAD

**Issue by kubasvoboda** [Sorashi/KasiopeaApi#1]
Ahoj, 
v Kasiopee se nám líbí co jsi udělal.
Mohlo by to některé účastníky potěšit a pomoct jim.
Můžeme dát odkaz na KasiopeApi na naše stránky?

Taky by jsme rádi věděli kdo jsi a co studuješ.

Za Kasiopeu,
Kuba

**Comment by sorashi** [comment]
Ahoj,
určitě, odkaz na stránky dát můžete.

**Comment by kubasvoboda** [comment]
Díky moc, je to na stránkách v sekci tipy a triky.
